name: UUIDSync
version: 1.0
main: com.RockySMP.UUID.uUIDSync.UUIDSync
api-version: 1.20
commands:
  linkdiscord:
    description: Link your Minecraft account with a Discord ID.
    usage: /linkdiscord <Discord ID>
  checklink:
    description: Check the link status of your account.
    usage: /checklink
  dbstatus:
    description: Zeige den Status der Datenbankverbindung an.
    usage: /dbstatus